branch-defaults:
  main:
    environment: Neeroai-env
environment-defaults:
  Neeroai-env:
    branch: null
    repository: null
global:
  application_name: neeroai
  default_ec2_keyname: neero-dev
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
