name: Deploy to ECR
on:
  push:
    branches: [ master ]
jobs:
  Pipeline:
    
    name: Pipeline
    runs-on: ubuntu-latest
    steps:

    - name: start pipeline
      run: echo "comienzo de pipeline"

    - name: Checkout
      uses: actions/checkout@v4

    - name: local env
      run: cat .env >> $GITHUB_ENV

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: docker build image
      run: docker build . -t $DOCKER_NAME:$VERSION -t $DOCKER_NAME:latest

    - name: docker push image
      run: docker push $DOCKER_NAME --all-tags

    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 3.82.152.199
        username: ubuntu
        key: ${{ secrets.ECS_SSH_KEY_PAIR }}
        script: |
          cd /home/ubuntu/server/apps/felipe-test 
          ls -all
          ecrlogin || true
          stackup felipe-test || true
          
      
