name: Deploy to ECR
on:
  push:
    branches: [ master ]
jobs:
  Pipeline:
    
    name: Pipeline
    runs-on: ubuntu-latest
    steps:

    - name: start pipeline
      run: echo "comienzo de pipeline"
      
    - name: Check out code
      uses: actions/checkout@v2
